import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContext } from "@/context/AuthContext";
import { useAuth } from "@/hooks/useAuth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Login App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // const { user, login, logout, setUser } = useAuth();
  return (
   
        <html lang="en">
          {/* <AuthContext.Provider value={{ user, setUser }}> */}

          <body className={inter.className}> {children}</body>
          {/* </AuthContext.Provider> */}
        </html>

  );
}
